### ISSUE TITLE
Schema Drafts

### ISSUE THREAD

**Issue by jxhnkndl** [Serendipbrity/MindFlip#1]
# Schema Drafts
My mind tends to think **models -> API -> front end -> revise** so I had a few quick starter thoughts on the database schema. We'll have to properly define the MVP acceptance criteria to know exactly how the first round of schemas will look but some of the fields seem obviously necessary. Mongoose makes it really easy to adapt these on the fly so we don't need to worry too much about getting locked into these schemas like we might with MySQL. 

One curiosity I have is how you're imagining the flash cards would work. Would there be a single answer to a flash card that a user would have to type in manually or would it be more like a quiz where the user gets an array of choices to pick from? I accounted for both basic possibilities.

We can change any of this to fit your vision. Just consider this a quick morning draft! 

## User
| field | type + attributes | notes |
|---|---|---|
|`_id`| string, required, auto-created | |
|`username`| string, required | |
|`email`| string, required | |
|`password`| string, required | |
|`flashcards`| `[ Flashcard ]`| |
|`friends`| `[ User ]` | |
|---|---|---|
|`firstName`| string | optional, maybe for a greeting in the UI and a welcome email |
|`lastName`| string | optional ^^^ |
|`lastLogin`| date | for calculating the streak you mentioned |
|`currentStreak`| number | post mvp feature |
|`longestStreak`| number | post mvp feature |

## Flashcard
| field | type + attributes | notes |
|---|---|---|
|`_id`| string, required, auto-created | |
|`question`| string, required | |
|`answer`| string, required ** | if you're thinking the user has to input the answer themselves |
|`category`| string | might be smart to batch flashcards early in the process |
|`user`| `User` | |

## Category (optional)
| field | type + attributes | notes |
|---|---|---|
|`_id`| string, required, auto-created | |
|`category`| string, required | |
|`flashcards`| `[ Flashcard ]` | would allow us to easily query every flashcard that belongs to a specific category; no specific feature in mind here yet, just an easy thing to consider early in the process that might make implementing certain types of features easier down the line |

**Comment by Serendipbrity** [comment]
So I’m more so thinking that they would input the answers when they make
the cards. Then they’d swipe like tinder to keep track of if they got them
right or wrong. They could lie but that wouldn’t help them actually learn
so that’s on them if they lie lmao it wouldn’t be so much a test as much as
literal virtual flash cards with a single set answer on the back. Ideally
I’d like the option for the back of the card input to be an image. Because
learning visually is helpful. But that can be put in later.

**Comment by Serendipbrity** [comment]
My thought process in reference to the id field is that since they are auto generated that we didnt necessarily need to add them in the models. But lmk if you think we still should

**Comment by Serendipbrity** [comment]
Lets implement the streaks after the MVP.

**Comment by jxhnkndl** [comment]
Got it. So a single answer field that stores a string most likely. 

Images could be cool. Would the user upload them or provide a link? I don't know much about how to upload files or whether that's something Mongo is good at but we could definitely look into it. 

Agreed about saving the streaks for a later round of feature updates. I figured if it was something we knew that we'd eventually try to do it wouldn't hurt to include the fields we'd likely need in the model. 

You can ignore the `_id` fields in the schema. You're totally right that we won't create them ourselves. It's just out of habit that I include them in the working models!

**Comment by Serendipbrity** [comment]
So I thought about the link vs the upload and based on the fact that the
app would need to be quick (“flushable”), and that I don’t want them to
have to follow a link to view the image, they should be able to upload
pictures. We can also implement this later. I looked in to it a bit and it
is possible to do with mongoDB. I agree that we could set things up for
future features. I like the idea of pre setting everything up for future
features. But, it also could (potentially) make the MVP more complicated in
debugging.

**Comment by jxhnkndl** [comment]
Yeah, plus by using links we'd probably be opening ourselves up to a broad range of predictable errors since we wouldn't be in control of what happens to the images after they've been added to cards. I'll look into the uploading thing a little bit too. That's something I've been curious about for a while now actually. When you were researching images and Mongo did you get a general sense for how complex accomplishing something like that might be? 

We can definitely set anything that isn't relevant aside until we've got a working MVP. Totally agree that there's no need to overcomplicate things. Just consider this me catching up to what you were imagining so that I can help you make it happen! 🙂

**Comment by Serendipbrity** [comment]
I didnt research extensively but from what I read, people were saying that it wasnt too hard
